---
- name: Create global operators
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
    - ./files/pipelines_subscription.yaml
    - ./files/odh_subscription.yaml
    - ./files/seldon_subscription.yaml
    - ./files/nfd_subscription.yaml

- name: "Wait for ODH operator to be Succeeded"
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: opendatahub-operator.v0.8.0
    namespace: openshift-operators
  register: result
  until: result | json_query("resources[0].status.phase=='Succeeded'")
  retries: 40
  delay: 10
    
- name: "Wait for nfd operator to be Succeeded"
  k8s_info:
    kind: Pod
    api_version: v1
    namespace: openshift-operators
    label_selectors:
      - name = nfd-operator    
    field_selectors:
      - status.phase=Running  
  register: result
  until: result.resources | length == 1
  retries: 40
  delay: 10
    
- name: Create NFD Custom Resource
  k8s:
    state: present
    definition: "{{ lookup('file', 'files/nfd_cr.yaml' ) | from_yaml }}"

- name: "Wait for nfd workers to be running"
  k8s_info:
    kind: Pod
    api_version: v1
    namespace: openshift-operators
    label_selectors:
      - app = nfd-worker
    field_selectors:
      - status.phase=Running
  register: result
  until: result.resources | length == (num_worker_nodes | int)
  retries: 40
  delay: 10