---
- name: Check whether mlflow is installed
  command: helm list -n {{demo_ns}} --filter mlflow --deployed
  register: results

- name: Install mlflow 
  command: helm install mlflow rhmlops/mlflow -n {{demo_ns}}
  when: "'deployed' not in results.stdout"
  
- name: Wait for mlflow to be ready
  uri:
    url: https://mlflow-{{demo_ns}}.{{ route_subdomain }}/
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 50
  delay: 10
  when: "'deployed' not in results.stdout"
  
