---
become_override: no
ocp_username: opentlc-mgr
silent: False

num_users: 10

module_type: m1

#
# All modules. Do NOT use a comma (,) in the titles or paths!
#
module_titles:
  - { name: m1, title: "Optimizing Existing Applications", path: /workshop/cloudnative/lab/workshop-environment }
  - { name: m2, title: "Debugging | Monitoring | Continuous Delivery", path: /workshop/cloudnative/lab/workshop-environment }
  - { name: m3, title: "Control Cloud Native Apps with Service Mesh", path: /workshop/cloudnative/lab/workshop-environment }
  - { name: m4, title: "Advanced Cloud-Native with Event-Driven Serverless", path: /workshop/cloudnative/lab/workshop-environment }

guid: 1002
gogs_admin_user: opentlc-mgr
gogs_admin_password: 'r3dh4t1!'
gogs_pwd: 'r3dh4t1!'
tmp_dir: /tmp/{{ guid }}

repositories:
  - base: https://github.com/tsailiming/
    name: datascience-examples
  
workshop_openshift_user_name: userXX
workshop_openshift_user_password: 'r3dh4t1!'
workshop_che_user_name: userXX
workshop_che_user_password: 'r3dh4t1!'
#workshop_rhamt_user_password: 'r3dh4t1!'

