ceph_namespace: openshift-storage
ceph_expected_crds:
- ocsinitializations.ocs.openshift.io
- storageclusters.ocs.openshift.io
- storageclusterinitializations.ocs.openshift.io

ceph_osd:
  resources:
    requests:
      cpu: '0.1'
      memory: 2Gi
ceph_mon:
  resources:
    requests:
      cpu: '0.2'
      memory: 3Gi
ceph_mgr:
  resources:
    requests:
      cpu: '0.2'
      memory: 3Gi
ceph_mds:
  resources:
    requests:
      cpu: '0.1'
      memory: 2Gi
noobaa_core:
  resources:
    requests:
      cpu: '0.2'
      memory: 2Gi
noobaa_db:
  resources:
    requests:
      cpu: '0.2'
      memory: 2Gi
noobaa_endpoint:
  resources:
    requests:
      cpu: '0.2'
      memory: 2Gi
ocs_version: 4.3
ocs_operator_channel: "stable-{{ocs_version}}"
ceph_storage_requests: 100Gi
ocs_source_namespace: openshift-marketplace
ocs_source: redhat-operators
set_cephfs_default_sc: false