---
- name: Check if repository {{ repository.name }} exists in git for user {{ user }}
  uri:
    url: https://gogs-labs-infra.{{ route_subdomain }}/api/v1/repos/{{ user }}/{{ repository.name }}
    user: "{{ user }}"
    password: "{{ gogs_pwd }}"
    force_basic_auth: true
    status_code: 200,404
  register: repo_result

- name: Create git repository {{ repository.name }} for user "{{ user }}"
  uri:
    url: https://gogs-labs-infra.{{ route_subdomain }}/api/v1/user/repos
    method: POST
    body: '{"name": "{{ repository.name }}", "private": false}'
    body_format: json
    user: "{{ user }}"
    password: "{{ gogs_pwd }}"
    status_code: 200,201
    force_basic_auth: true
  when: repo_result.status != 200

- name: Create repositories
  git:
    repo: "{{ repository.base }}/{{ repository.name }}"
    dest: "{{ tmp_dir }}/{{ repository.name }}"
    force: true

- name: Push {{ repository.name }} to git repository in Gogs for user "{{ user }}"
  shell: |
    git remote add {{ user }} https://{{ user }}:{{ gogs_pwd }}@gogs-labs-infra.{{ route_subdomain }}/{{ user }}/{{ repository.name }}.git
    git config --local user.email "{{ user }}@example.com"
    git config --local user.name "{{ user }}"
    git push -f --all {{ user }}
  args:
    chdir: "{{ tmp_dir }}/{{ repository.name }}"
  when: repo_result.status != 200    