---
- name: Create configmap for {{user}} in {{ns}}
  k8s:
    state: present
    definition: 
      kind: ConfigMap
      apiVersion: v1
      metadata:
        namespace: "{% if ns!='labs-infra' %}{{user}}-{{ns}}{% else %}{{ns}}{% endif %}"
        name: "{% if ns!='labs-infra' %}mlflow-cm{% else %}{{user}}-mlflow-cm{% endif %}"
      data:
        MLFLOW_S3_ENDPOINT_URL: "https://s3-openshift-storage.{{route_subdomain}}"
        MLFLOW_TRACKING_URI: "https://mlflow-{{user}}-dev.{{ route_subdomain }}"
        S3_ENDPOINT_URL: "https://s3-openshift-storage.{{route_subdomain}}"
        DATA_REPO: "https://gogs-labs-infra.{{ route_subdomain }}/{{user}}/creditcard"
        WORKSHOP_USER_ID: "{{user}}"
        SELDON_STAGE_URL: "https://seldon-{{USER}}-stage.{{route_subdomain}}"
        SELDON_PROD_URL: "https://seldon-{{USER}}-prod.{{route_subdomain}}"