---
# Deploy AMQ Streams Operator
- name: Create operator subscription for AMQ Streams
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
  - ./files/amq_streams_operatorgroup.yaml
  - ./files/amq_streams_subscription.yaml

# Wait for CRD
- name: Wait for AMQ Streams CRD to be ready
  k8s_facts:
    api_version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: kafka.v1beta1.kafka.strimzi.io
  register: r_amqstreams_crd
  retries: 200
  delay: 10
  until: r_amqstreams_crd.resources | list | length == 1
