---
- name: create project
  k8s:
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "{{item}}"
        annotations:
          openshift.io/description: ""
          openshift.io/display-name: "Lab Infrastructure"
        labels:
          prometheus.io/scrape: "true"
  loop:
    - labs-grafana
    - labs-prometheus

- name: Create operator subscription for ODH
  k8s:
    state: present
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
    - ./files/odh_subscription.yaml

- name: "Wait for ODH operator to be Succeeded"
  k8s_facts:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: opendatahub-operator.v0.6.1
    namespace: openshift-operators
  register: result
  until: result | json_query("resources[0].status.phase=='Succeeded'")
  retries: 40
  delay: 10

- name: Create prometheus instance
  k8s:
    state: present    
    definition: "{{ lookup('file', './files/prom_kfdef.yaml' ) | from_yaml }}"

- name: Create grafana instance
  k8s:
    state: present    
    definition: "{{ lookup('file', './files/grafana_kfdef.yaml' ) | from_yaml }}"

- name: Create seldon instance
  k8s:
    state: present    
    definition: "{{ lookup('file', './files/seldon_kfdef.yaml' ) | from_yaml }}"

- name: "Wait for prometheus operator to be Succeeded"
  k8s_facts:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: prometheusoperator.0.37.0
    namespace: labs-prometheus
  register: result
  until: result | json_query("resources[0].status.phase=='Succeeded'")
  retries: 40
  delay: 10

- name: Patch operator group to watch ns that are labeled
  k8s:
    merge_type: merge    
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: opendatahub
        namespace: labs-prometheus
      spec:
        selector:
          matchLabels:
            prometheus.io/scrape: 'true'
        targetNamespaces:

- name: Patch csv with MultiNamespace
  k8s:
    merge_type: merge    
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      metadata:
        name: prometheusoperator.0.37.0
        namespace: labs-prometheus
      spec:
        installModes:
          - supported: true
            type: OwnNamespace
          - supported: true
            type: SingleNamespace
          - supported: true
            type: MultiNamespace
          - supported: false
            type: AllNamespaces

- name: Create ServiceMonitor
  k8s:
    state: present
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: odh-seldon
        namespace: "{{ item[0] }}-{{ item[1] }}"
      spec:
        endpoints:
          - interval: 30s
            path: /prometheus
            port: http
            scheme: http
        selector:
          matchExpressions:
            - key: model
              operator: DoesNotExists        
            - key: seldon-app
              operator: Exists
  loop: "{{ users|product(['dev', 'staging', 'prod'])|list }}"
