---
# Deploy Business Automation (DM) Operator
- name: Create operator subscription for Decision Manager
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
  - ./files/dm_operatorgroup.yaml
  - ./files/dm_subscription.yaml

# Wait for CRD
- name: Wait for Decision Manager CRD to be ready
  k8s_facts:
    api_version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: kieapps.app.kiegroup.org
  register: r_dm_crd
  retries: 200
  delay: 10
  until: r_dm_crd.resources | list | length == 1

# Install DM CR
- name: Create CR for DM
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
  - ./files/dm_cr.yaml

# Wait for DM kieserver pod to be up
- name: "Wait for DM kieserver pod to be in Ready state"
  k8s_info:
    kind: Pod
    label_selectors:
      - 'service = dm-kieserver'
    namespace: labs-dm
  register: pod_status
  until: pod_status.resources[0].status.containerStatuses[0].ready == true
  retries: 60
  delay: 10

# Wait for DM rhdmcentr pod to be up
- name: "Wait for DM rhdmcentr pod to be in Ready state"
  k8s_info:
    kind: Pod
    label_selectors:
      - 'service = dm-rhdmcentr'
    namespace: labs-dm
  register: pod_status
  until: pod_status.resources[0].status.containerStatuses[0].ready == true
  retries: 60
  delay: 10
