---
# Setup Seldon via operator
- name: Create OpenShift Objects for pipelines
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
    - ./files/pipelines_subscription.yaml
    - ./files/odh_subscription.yaml
    - ./files/seldon_subscription.yaml
    
