apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  name: v1beta1.kwkoo.github.com
spec:
  group: kwkoo.github.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: pipelinerestrictor
    namespace: labs-infra
  version: v1beta1