apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:  
  name: prometheus-operator
  namespace: labs-prometheus
spec:
  channel: beta
  installPlanApproval: Automatic
  name: prometheus
  source: prometheus-operator
  sourceNamespace: openshift-marketplace
  startingCSV: prometheusoperator.0.37.0