apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: odh-prometheus
  namespace: labs-prometheus
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: prometheus/cluster
      name: prometheus-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: prometheus/operator
      name: prometheus-operator
  repos:
    - name: manifests
      uri: https://github.com/tsailiming/odh-manifests/tarball/master