---
- name: Discovering worker nodes
  k8s_facts:
    api_version: v1
    kind: Node
    label_selectors:
    - node-role.kubernetes.io/worker
  register: worker_nodes

- fail:
    msg: "Less than 3 worker nodes detected. Cannot install Ceph..."
  when: worker_nodes | length < 3

- set_fact:
    ceph_worker_nodes: "{{ worker_nodes | json_query('resources[*].metadata.name') }}"

- name: "Adding Ceph labels to worker nodes"
  shell: "oc label nodes --overwrite {{ item }} cluster.ocs.openshift.io/openshift-storage=''"
  loop: "{{ ceph_worker_nodes[:3] }}"

# Create Namespace
- name: "Creating namespace"
  k8s:
    definition:  
      metadata:
        name: "{{ ceph_namespace }}"
        apiVersion: v1
        labels:
          openshift.io/cluster-monitoring: 'true'
      kind: Namespace
    state: present

- name: pre_workload Tasks Complete
  debug:
    msg: "Pre-Software checks completed successfully"
